title: AI networking library by Leslie lyu
description: Ai data center network engineering learner!
url: https://leslie-2027.github.io
locale: zh-CN
timezone: Asia/Shanghai
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
author:
  name: Leslie
  bio: i love network engineering !
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
paginate: 5
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
